# Use Tomcat as the base image
FROM tomcat:9-jdk11-openjdk

# Set the maintainer label (optional)
LABEL maintainer="vijay.com"


# Copy the WAR file generated by Maven into Tomcat's webapps directory
COPY ./target/spareparts.war /usr/local/tomcat/webapps

EXPOSE 8080

